name: dart_amqp
description: >
  A native dart AMQP client supporting version 0.9.1 of the AMQP protocol. It features an asynchronous API, pluggable authentication providers and TLS support.
version: 0.2.5
homepage: https://github.com/achilleasa/dart_amqp
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  async: ^2.10.0
  logging: ^1.0.1
dev_dependencies:
  test: ^1.17.5
  mockito: ^5.0.9
  http: ^0.13.3
  xml: ^5.1.1
  lints: ^2.0.1
false_secrets:
  - test/lib/mocks/certs/*.pem
